/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as MembersRouteImport } from './routes/members'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ExhibitorsRouteImport } from './routes/exhibitors'
import { Route as EpassStatusRouteImport } from './routes/epass-status'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsYearRouteImport } from './routes/events.$year'

const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitorsRoute = ExhibitorsRouteImport.update({
  id: '/exhibitors',
  path: '/exhibitors',
  getParentRoute: () => rootRouteImport,
} as any)
const EpassStatusRoute = EpassStatusRouteImport.update({
  id: '/epass-status',
  path: '/epass-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsYearRoute = EventsYearRouteImport.update({
  id: '/events/$year',
  path: '/events/$year',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/epass-status': typeof EpassStatusRoute
  '/exhibitors': typeof ExhibitorsRoute
  '/gallery': typeof GalleryRoute
  '/members': typeof MembersRoute
  '/upcoming': typeof UpcomingRoute
  '/visitors': typeof VisitorsRoute
  '/events/$year': typeof EventsYearRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/epass-status': typeof EpassStatusRoute
  '/exhibitors': typeof ExhibitorsRoute
  '/gallery': typeof GalleryRoute
  '/members': typeof MembersRoute
  '/upcoming': typeof UpcomingRoute
  '/visitors': typeof VisitorsRoute
  '/events/$year': typeof EventsYearRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/epass-status': typeof EpassStatusRoute
  '/exhibitors': typeof ExhibitorsRoute
  '/gallery': typeof GalleryRoute
  '/members': typeof MembersRoute
  '/upcoming': typeof UpcomingRoute
  '/visitors': typeof VisitorsRoute
  '/events/$year': typeof EventsYearRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/epass-status'
    | '/exhibitors'
    | '/gallery'
    | '/members'
    | '/upcoming'
    | '/visitors'
    | '/events/$year'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/epass-status'
    | '/exhibitors'
    | '/gallery'
    | '/members'
    | '/upcoming'
    | '/visitors'
    | '/events/$year'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/epass-status'
    | '/exhibitors'
    | '/gallery'
    | '/members'
    | '/upcoming'
    | '/visitors'
    | '/events/$year'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EpassStatusRoute: typeof EpassStatusRoute
  ExhibitorsRoute: typeof ExhibitorsRoute
  GalleryRoute: typeof GalleryRoute
  MembersRoute: typeof MembersRoute
  UpcomingRoute: typeof UpcomingRoute
  VisitorsRoute: typeof VisitorsRoute
  EventsYearRoute: typeof EventsYearRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitors': {
      id: '/exhibitors'
      path: '/exhibitors'
      fullPath: '/exhibitors'
      preLoaderRoute: typeof ExhibitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epass-status': {
      id: '/epass-status'
      path: '/epass-status'
      fullPath: '/epass-status'
      preLoaderRoute: typeof EpassStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$year': {
      id: '/events/$year'
      path: '/events/$year'
      fullPath: '/events/$year'
      preLoaderRoute: typeof EventsYearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EpassStatusRoute: EpassStatusRoute,
  ExhibitorsRoute: ExhibitorsRoute,
  GalleryRoute: GalleryRoute,
  MembersRoute: MembersRoute,
  UpcomingRoute: UpcomingRoute,
  VisitorsRoute: VisitorsRoute,
  EventsYearRoute: EventsYearRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
